services:
  - type: web
    name: taskmanager-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/taskmanager-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
    plan: free
